# Generated by Django 4.2.2 on 2023-06-17 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_mimodelo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mimodelo',
            old_name='campo2',
            new_name='Estado',
        ),
        migrations.RenameField(
            model_name='mimodelo',
            old_name='campo1',
            new_name='IdEstado',
        ),
    ]
