# Generated by Django 4.2.2 on 2023-07-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoRequerido',
            fields=[
                ('documento_requerido_id', models.AutoField(primary_key=True, serialize=False)),
                ('documento_requerido', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'documento_requerido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPersona',
            fields=[
                ('tipo_persona_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_persona', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tipo_persona',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Codigospostales',
        ),
    ]
